version: "3.8"

x-common-neo4j-connection-environment: &common-neo4j-connection-environment
  HOST: "${HOST:-localhost}"
  HTTP_PORT: "${HTTP_PORT:-7474}"
  BOLT_PORT: "${BOLT_PORT:-7687}"
  # https://neo4j.com/docs/operations-manual/4.4/docker/ref-settings/
  NEO4J_dbms_default__listen__address: "${NEO4J_dbms_default__listen__address:-0.0.0.0}"
  NEO4J_dbms_default__advertised__address: "${NEO4J_dbms_default__advertised__address:-localhost}"
  NEO4J_dbms_connector_http_listen__address: "${NEO4J_dbms_connector_http_listen__address:-:7474}"
  NEO4J_dbms_connector_http_advertised__address: "${NEO4J_dbms_connector_http_advertised__address:-:7474}"
  NEO4J_dbms_connector_bolt_listen__address: "${NEO4J_dbms_connector_bolt_listen__address:-:7687}"
  NEO4J_dbms_connector_bolt_advertised__address: "${NEO4J_dbms_connector_bolt_advertised__address:-:7687}"

x-admin-neo4j-connection-environment: &admin-neo4j-connection-environment
  ADMIN_NEO4J_USERNAME: "${ADMIN_NEO4J_USERNAME:-neo4j}"
  ADMIN_NEO4J_PASSWORD: "${ADMIN_NEO4J_PASSWORD:-graph}"
  NEO4J_AUTH: "${ADMIN_NEO4J_USERNAME:-neo4j}/${ADMIN_NEO4J_PASSWORD:-graph}"

x-graph-neo4j-connection-environment: &graph-neo4j-connection-environment
  GRAPH_NEO4J_USERNAME: "${GRAPH_NEO4J_USERNAME:-graph}"
  GRAPH_NEO4J_PASSWORD: "${GRAPH_NEO4J_PASSWORD:-graph}"
  GRAPH_NEO4J_DATABASE: "${GRAPH_NEO4J_DATABASE:-graph}"
  NEO4J_dbms_default__database: "${GRAPH_NEO4J_DATABASE:-graph}"

x-neo4j-ports: &neo4j-ports
  # https://neo4j.com/docs/operations-manual/4.4/configuration/ports/
  ports:
    - "${HTTP_PORT:-7474}:${HTTP_PORT:-7474}"
    - "${BOLT_PORT:-7687}:${BOLT_PORT:-7687}"

services:
  neo4j:
    image: neo4j:4.4-community
    restart: always
    environment:
      <<: *common-neo4j-connection-environment
      <<: *admin-neo4j-connection-environment
      <<: *graph-neo4j-connection-environment
    <<: *neo4j-ports
    volumes:
      - "graph_db_data:/data"
      - "./docker/neo4j/cypher-scripts:/neo4j/cypher-scripts"
      - "./docker/neo4j/start:/neo4j/start"
    entrypoint: [ "/neo4j/start/docker-entrypoint.sh" ]

volumes:
  graph_db_data:
    name: graph_db_data
